spring.application.name=atlas
spring.datasource.url=jdbc:h2:mem:telemetrydb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042

spring.cassandra.keyspace-name=atlas

spring.cassandra.local-datacenter=datacenter1